Repository Challengers-BOD/BOD, pull requests merged in 2024-08, with the labels that each got.

#98 #96feature/users/challenge get statusbefore
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/user/service/UserServiceImpl.java
Labels: feat

#99 #13feature/admin/users/get
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminUserUpdateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminUserUpdateResponseDto.java
  src/main/java/com/bod/bod/admin/dto/AdminUsersResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/user/entity/User.java
Labels: refactor

#101 #100refactor/challenge/pagination
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/dto/PaginationResponse.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepository.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepositoryImpl.java
Labels: refactor

#105 #104fix/verification
  src/main/java/com/bod/bod/verification/repository/VerificationRepository.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: fix

#106 #13feature/admin/users/get
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
Labels: refactor

#108 #107feature/challenge verification/status
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/verification/controller/VerificationController.java
  src/main/java/com/bod/bod/verification/dto/VerificationWithChallengeResponseDto.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepository.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepositoryImpl.java
  src/main/java/com/bod/bod/verification/repository/VerificationRepository.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: feat

#113 #107feature/challenge 인증취소시 예외처리 추가
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/verification/dto/VerificationWithChallengeResponseDto.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: feat

#119 #118feature/users/get ranking point
  build.gradle
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/global/config/RedisConfig.java
  src/main/java/com/bod/bod/user/controller/UserController.java
  src/main/java/com/bod/bod/user/dto/PointRankingResponseDto.java
  src/main/java/com/bod/bod/user/service/UserService.java
  src/main/java/com/bod/bod/user/service/UserServiceImpl.java
Labels: feat

#124 refactor / 매개변수명 수정하여 대상 명확하게 표시, 전체조회 페이지네이션 로직 수
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/dto/PaginationResponse.java
  src/main/java/com/bod/bod/user/repository/UserRepository.java
  src/main/java/com/bod/bod/verification/controller/VerificationController.java
  src/main/java/com/bod/bod/verification/repository/VerificationRepository.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: refactor

#126 #118feature/users/get ranking point
  src/main/java/com/bod/bod/global/config/RedisConfig.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/user/dto/PointRankingResponseDto.java
  src/main/java/com/bod/bod/user/repository/UserRepository.java
  src/main/java/com/bod/bod/user/service/UserServiceImpl.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: feat

#129 feat / 챌린지 참가 인원 제한 기능구현, 비관적 락 으로 동시성 제어 구현
  src/main/java/com/bod/bod/admin/dto/AdminChallengeCreateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeCreateResponseDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeResponseDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeUpdateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeUpdateResponseDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengesResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeSummaryResponseDto.java
  src/main/java/com/bod/bod/challenge/entity/Challenge.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
Labels: feat

#131 #130feature/signup email
  build.gradle
  src/main/java/com/bod/bod/global/config/MailConfig.java
  src/main/java/com/bod/bod/global/config/RedisConfig.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/global/jwt/security/RedisEmailAuthentication.java
  src/main/java/com/bod/bod/user/controller/SignupController.java
  src/main/java/com/bod/bod/user/dto/EmailAddressDto.java
  src/main/java/com/bod/bod/user/dto/EmailAuthenticationDto.java
  src/main/java/com/bod/bod/user/dto/EmailDto.java
  src/main/java/com/bod/bod/user/service/MailService.java
  src/main/java/com/bod/bod/user/service/MailServiceImpl.java
  src/main/java/com/bod/bod/user/service/SignupService.java
  src/main/java/com/bod/bod/user/service/SignupServiceImpl.java
Labels: feat

#137 refactor : 챌린지등록, 인증요청 이미지 업로드 기능분리 리팩토링
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/global/exception/GlobalExceptionHandler.java
  src/main/java/com/bod/bod/global/exception/InvalidFileTypeException.java
  src/main/java/com/bod/bod/global/service/S3Service.java
  src/main/java/com/bod/bod/global/service/S3ServiceImpl.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
  src/main/resources/application-docker.properties
Labels: refactor

#145 #144fix/verification/get top3 verification users
  src/main/java/com/bod/bod/verification/dto/VerificationTop3UserResponseDto.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepositoryImpl.java
Labels: fix

#147 #146 어드민 챌린지 수 카운트 기능 구현
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeCountResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/global/config/WebSecurityConfig.java
Labels: feat

#149 #148 어드민 유저 카운트 기능 구현
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminUserCountResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/user/repository/UserRepository.java
Labels: feat

#150 #144fix/verification/get top3 verification users
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/global/service/S3ServiceImpl.java
  src/main/java/com/bod/bod/user/dto/PointRankingResponseDto.java
Labels: fix

#154 #153fix/image upload
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/global/service/S3Service.java
  src/main/java/com/bod/bod/global/service/S3ServiceImpl.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: fix

#158 #157feature/challenges/search by title
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
Labels: feat
