Repository Challengers-BOD/BOD, pull requests merged in 2024-07, with the labels that each got.

#20 #3 feature/admin/challenge/post
  .gitignore
  build.gradle
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/bod/bod/challenge/entity/Category.java
  src/main/java/com/bod/bod/challenge/entity/Challenge.java
  src/main/java/com/bod/bod/challenge/entity/ConditionStatus.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/user/entity/Status.java
  src/main/resources/application-secret.properties
  src/main/resources/application.properties
Labels: feat

#24 #17feature/get challenges/category
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeSummaryResponseDto.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepository.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/config/QueryDSLConfig.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
Labels: feat

#25 #12feature/get all challenges
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepository.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/dto/CommonResponseDto.java
Labels: feat

#27 #26feature/get all challenges 챌린지 단건 상세조회 구현
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeRepository.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
Labels: feat

#32 #13feature/admin/users/get
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminUsersResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/user/repository/UserRepository.java
  src/main/resources/application-secret.properties
Labels: feat

#33 feat / 어드민 특정 회원 정보 수정 기능 구현
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminUserUpdateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminUserUpdateResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
Labels: feat

#34 #28feature/request verification 챌린지 인증요청 구현
  build.gradle
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/config/S3Config.java
  src/main/java/com/bod/bod/global/exception/FileUploadFailureException.java
  src/main/java/com/bod/bod/global/exception/GlobalExceptionHandler.java
  src/main/java/com/bod/bod/verification/controller/VerificationController.java
  src/main/java/com/bod/bod/verification/dto/VerificationRequestDto.java
  src/main/java/com/bod/bod/verification/dto/VerificationResponseDto.java
  src/main/java/com/bod/bod/verification/entity/Verification.java
  src/main/java/com/bod/bod/verification/repository/VerificationRepository.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
  src/main/resources/application-secret.properties
Labels: feat

#45 #44fix/request verification 예외처리 수정
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/verification/entity/Verification.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: fix

#52 #51refactor/verification exception
  src/main/java/com/bod/bod/global/exception/ErrorCode.java
  src/main/java/com/bod/bod/verification/entity/Verification.java
  src/main/java/com/bod/bod/verification/repository/VerificationRepository.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: fix, refactor

#53 #51refactor/verification exception 인증 목록 조회시 imageUrl 반환 / 인증 필드 +imageUrl,imageName 수정
  src/main/java/com/bod/bod/admin/dto/AdminVerificationGetResponse.java
  src/main/java/com/bod/bod/verification/dto/VerificationWithUserResponseDto.java
  src/main/java/com/bod/bod/verification/entity/Verification.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepositoryImpl.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: fix

#81 #80feature/getchallenge top10
  src/main/java/com/bod/bod/challenge/controller/ChallengeController.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepository.java
  src/main/java/com/bod/bod/challenge/repository/ChallengeCustomRepositoryImpl.java
  src/main/java/com/bod/bod/challenge/service/ChallengeService.java
  src/main/java/com/bod/bod/global/config/WebConfig.java
Labels: feat

#85 update : 챌린지 등록시 이미지 등록 및 삭제기능 추가
  build.gradle
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeCreateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeCreateResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/challenge/entity/Challenge.java
  src/main/java/com/bod/bod/global/config/S3Config.java
  src/main/java/com/bod/bod/verification/controller/VerificationController.java
  src/main/java/com/bod/bod/verification/dto/VerificationRequestDto.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: feat

#88 refactor / 어드민 챌린지 전체조회 페이지값 변경, CorsMapping "PATCH" 타입 추가
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/global/config/WebSecurityConfig.java
Labels: refactor

#89 #76feature/admin/challenges
  src/main/java/com/bod/bod/admin/dto/AdminChallengeUpdateRequestDto.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeUpdateResponseDto.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
  src/main/java/com/bod/bod/challenge/entity/Challenge.java
Labels: refactor

#91 #90feature/admin/challenge/get
  src/main/java/com/bod/bod/admin/controller/AdminController.java
  src/main/java/com/bod/bod/admin/dto/AdminChallengeResponseDto.java
  src/main/java/com/bod/bod/admin/dto/AdminVerificationGetResponse.java
  src/main/java/com/bod/bod/admin/service/AdminService.java
Labels: feat

#93 #92feature/challenge/verification top3 users
  src/main/java/com/bod/bod/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/bod/bod/challenge/dto/ChallengeSummaryResponseDto.java
  src/main/java/com/bod/bod/verification/controller/VerificationController.java
  src/main/java/com/bod/bod/verification/dto/VerificationTop3UserResponseDto.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepository.java
  src/main/java/com/bod/bod/verification/repository/VerificationCustomRepositoryImpl.java
  src/main/java/com/bod/bod/verification/service/VerificationService.java
Labels: feat

#94 refactor / 관리자 인증요청목록 조회에 유저네임 추가
  src/main/java/com/bod/bod/admin/dto/AdminVerificationGetResponse.java
Labels: refactor
